package-lock.json
package.json

The project seems unmaintained and depends on Elm 0.18, which is (for unknown reason) attempts to download from bintray which is being shut down (responds with HTTP 403).

Remove broken (and unused) dependency 'elm-typescript-interop'

---

README.md
elm.json
src/client/elm/Explorer/Request.elm
src/client/elm/Explorer/View.elm
src/client/elm/Transaction/Event.elm
src/client/elm/Transaction/Summary.elm
tests/Explorer/ViewTest.elm

Displays two new update transaction types: for adding new anonymity revokers, and for adding new identity providers. This addresses #4.
In addition to the above, updates README links to point from gitlab to github repositories, and fixes a typo in the `viewEventUpdateEnueuedDetails` function name.
Note: I'm adding this as a merge to `overflow-fix` (#6) to make it easier to review.

Support for AR and IP update transactions.

---

src/client/elm/Explorer/View.elm

In the `AmountTooLarge` rejected transaction case, we say that the account has insufficient funds. In the case where a baker has a large account balance that is staked, they might wonder why their transfer didn't get through. I want to clarify that the insufficient-balance error refers to nonstaked funds.

Clarifying that insufficient funds refer to nonstaked funds.

---

src/client/elm/Explorer/View.elm
src/client/elm/Transaction/Summary.elm

- Fix displaying of baker-stake-threshold update transactions (#12).
- Add support for missing reject reasons which also fixes #11.

Fix support for baker-stake-threshold update transaction, add support for missing reject reasons.

---

src/client/elm/Api.elm
src/client/elm/Explorer.elm
src/client/elm/Explorer/View.elm
src/client/elm/Main.elm
src/client/elm/TimeHelpers.elm

- Displaying the number of transactions in block explorer (#10).
- Removing milliseconds from time stamp. This removes, in my opinion, redundant information, and makes the line shorter, avoiding text overflow.
- Display error when exploring nonexisting blocks (#15)

Multiple block-explorer changes

---

src/client/elm/Config.elm
src/client/elm/Explorer/View.elm
tests/Explorer/ViewTest.elm

Making sure that transaction rendering doesn't introduce unnecessary line breaks introduced by #6, but ensuring that credential IDs are displayed without overflow, as mentioned in #5.
- Instead of using `paragraph` to render transactions, we use `wrappedRow` because it  doesn't introduce unnecessary line breaks (thanks @limemloh).
- Credential IDs take up more space than what fits in an `EVENTS` row; so we display only a prefix of the credential and display all of it in the transaction `details`:

Overflow fix revisited

---

src/client/elm/Explorer/Request.elm
src/client/elm/Explorer/View.elm
src/client/elm/Transaction/Event.elm
src/client/elm/Transaction/Summary.elm

Block explorer fails to decode blockSummary, when an update of foundation account is queued, because the dashboard assumes the foundation account to be an account address, but the api exposes the account index instead.
Show the foundation account index

Updating foundation account gives an index instead of an account

---

src/client/elm/Explorer/View.elm

This changes the way microGTU-to-Euro and Euro-to-NRG conversion rates are phrased and displayed (see screenshots).
Original:
Proposed:

Displaying conversion rate updates

---

src/client/elm/Config.elm

We are still using `.com` for stage- and testnet.
Closes #19 
Use `.com` instead of `.software`

Use .com in dashboard urls for stage- and testnet

---

CHANGELOG.md
src/client/elm/Explorer/View.elm

Make contract addresses copyable from the details view.
Closes #25 
- Make the addresses copyable.
- Allow the table contents to overflow when the number of rows is low. (This was necessary since the hover tooltips were being clipped)

Make contrAddr copyable in details

---

README.md
package-lock.json
package.json
webpack.config.js

Remove unmaintained dependency, since it is breaking a script on Ubuntu 20.10
See issue #52
- Remove dependency `open-browser-webpack-plugin`
- Update `package-lock.json`

Remove dependency open-browser-webpack-plugin

---

CHANGELOG.md
src/client/elm/Chain.elm
src/client/elm/Tooltip.elm

This addresses #53, adding a small info icon with a tooltip to the chain visualisation, explaining what the purple bars mean.
- Added purple info icon in the top right corner of the chain visualisation

Added an info icon and tooltip, explaining what the purple bars on blocks mean (#53)

---

CHANGELOG.md
src/client/elm/Transaction/Event.elm

Closes #69
- Decoding CBOR will encode the resulting value into bytes again and compare the length with the original byte input to ensure the whole bytestring is consumed.

Ensure every byte is decoded when decoding CBOR

---

CHANGELOG.md
src/client/elm/Explorer/View.elm
src/client/elm/Transaction/Event.elm

Closes #66.
- Rename the type for memo bytes `Memo` to `ArbitraryBytes`.
- Use `ArbitraryBytes` for the data in the register data event.
- Display details whether the bytes are interpreted as CBOR or raw.

Attempt to parse registerData as CBOR

---

src/client/elm/Explorer/View.elm

Closes #40 and closes #64.
Revert parts of PR #62 which allows words to break for every event displayed.
Instead, this is only set for contract names, contract events, memos and registered data
Blocks on testnet: 
- Large memo: ce6f805390b9c0ac42aefcbe7507391b90c4348f23b1c2be76b6030d5d6571a4
- Previously broken event: ef8faec0655b55422c50b14f0f9ab2df72d36fc38d92596345113aae2abec805
Blocks on stagenet:
- Long contract name: 5b4ef7078aec607a380350bfcb274b717b70f67945d6d68d8579f0a6e69bc5f7
*This is already in the changelog*

Revert the word break for all events and only set for relevant

---

webpack.config.js

When navigating to a deep link such as `/chain/ea596a8b25fbe94673651b3687e8a726810a732a0faee7ae86721af345c043cs` it would attempt to get resources relative to `/chain`.
This PR ensures the resources are absolute from `/`.
- Set absolute paths for webpack build
- Simplify `historyApiFallback` since we are using the default setting.

Make sure that deep links still fetches resources from root

---

CHANGELOG.md
package.json
src/elm/Lookup.elm
src/elm/Main.elm
src/elm/Types.elm

Add validation of user input when using transaction lookup.
Closes #38.
- Add function for validating a transaction hash.
Validation includes checking for hex string length is 64 characters and checking that every character is a hex-digit.
- Display error message when searching for invalid transaction hash.
- Move Lookup page initialization logic into `Lookup.elm`

Add validation of transaction lookup string

---

CHANGELOG.md
Jenkinsfile
README.md
k8s.Dockerfile
package.json
src/client.ts
src/elm/Context.elm
src/elm/Main.elm
src/elm/Network.elm
types.d.ts
webpack.config.js

Fixes #88 
Ignore old versions in statistics calculations. Introduces a new environment variable `STATS_VERSION`.

Ignore old nodes in computing summaries

---

CHANGELOG.md
package.json
src/elm/Explorer/View.elm

The CCD/EUR exchange rate should be shown as "1 EUR = X CCD" in update event list. 
Closes #94 
The exchange rate is received from the CCD2EUR services as a fraction, where the nominator stands for microCCDs, and the denominator stands for euro. To display the exchange rate as "1 EUR = X CCD", one takes the whole part of the nominator divided by the denominator. There's no loss of precision because we assume microCCDs to be the smallest unit of CCD.
By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

Display normalized EUR/CCD exchange rate

---

CHANGELOG.md
package.json
src/elm/Explorer/Request.elm
src/elm/Explorer/View.elm
src/elm/Transaction/Event.elm
src/elm/Transaction/Summary.elm
src/elm/Types.elm

These changes permit the dashboard to parse correctly the `blockSummary` API response V1, which accompanies the protocol V4. They include the display of `ConfigureBaker` and `ConfigureDelegation` transactions and of payday events, such as block rewards to pools and the foundation. 
Closes #91.
Closes #89  
The `ChainParameters` and `AccountTransactionType` types were updated to match their counterparts on the node side, together with the JSON decoders in Elm.
As the protocol V4 doesn't have a notion of per-slot minting, the dashboard doesn't display it anymore.
By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

Added support for protocol V4, including delegation

---

package.json
src/elm/Transaction/Summary.elm

JSON decoder fails because there was no handling of the "pool closed" reject reason. 
Adds the `PoolClosed` case in `rejectReasonDecoder`.
By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

Added handling PoolClosed to rejectReasonDecoder

---

CHANGELOG.md
src/elm/Network/NodesTable.elm

Closes #93
The node version column label in the node list is now "Node".
By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

Renamed "Client" row to "Node"

---

CHANGELOG.md
package-lock.json
package.json
src/elm/Explorer/View.elm
src/elm/Transaction/Event.elm

Handle the smart contract upgraded event
- Handle new event case
- Add a function for displaying module references similarly to how we display addresses. I.e. with a tooltip on hover and the ability to copy on click.
- I just used the smart contract symbol for this, but perhaps we should use something else? Any suggestions?

Handle smart contract upgraded event

---

CHANGELOG.md
package.json
src/elm/Api.elm

blockSlot is not used by the network dashboard, but it was still expected when parsing. This removes it to make the network dashboard work with  protocol 6.

Update network dashboard for protocol 6.
